#!/bin/sh

HYPR_LOG_DIR='/tmp/hypr'

function cancel {
    echo -e '\e[31mAbort.\e[0m'
    exit 1
}

echo -e '\e[33mStarting Hyprland...\e[0m \e[2m(Ctrl-C to cancel)\e[0m'
trap cancel SIGINT
read -t 1

if [[ ! -d "$HYPR_LOG_DIR" ]]; then
    mkdir -pm 777 "$HYPR_LOG_DIR" && chmod o+t "$HYPR_LOG_DIR"
fi
exec Hyprland > "$HYPR_LOG_DIR/hyprland-$$.log" 2>&1
