#!/bin/sh

HYPR_LOG_DIR='/tmp/hypr'

echo -e '\e[33mStarting Hyprland...\e[0m'
if [[ ! -d "$HYPR_LOG_DIR" ]]; then
    echo '-- create directory:' $HYPR_LOG_DIR
    mkdir -pm 777 "$HYPR_LOG_DIR" && chmod o+t "$HYPR_LOG_DIR"
fi
exec Hyprland > "$HYPR_LOG_DIR/hyprland-$$.log" 2>&1
exit 1
