#!/bin/bash

#
## Idle manager daemon
#

LOCK_TIMEOUT=900 # sec
DPMS_TIMEOUT=920 # sec
SLEEP_TIMEOUT=3600 # sec

if [[ "$XDG_CURRENT_DESKTOP" = 'Hyprland' ]]; then
    DPMS_ON_CMD='echo -n dpms on ...; hyprctl dispatch dpms on'
    DPMS_OFF_CMD='echo -n dpms off ...; hyprctl dispatch dpms off'
else
    echo 'unknown desktop:' $XDG_CURRENT_DESKTOP
    exit 1
fi

LOCK_PROG=hyprlock
LOCK_PROG_ARGS=(
    -q
)

pkill -x swayidle
exec swayidle -w \
    timeout $LOCK_TIMEOUT 'loginctl lock-session' \
    timeout $DPMS_TIMEOUT "$DPMS_OFF_CMD" resume "$DPMS_ON_CMD" \
    timeout $SLEEP_TIMEOUT 'systemctl suspend' \
    before-sleep 'loginctl lock-session' \
    after-resume "$DPMS_ON_CMD" \
    lock "pgrep -cx $LOCK_PROG || $LOCK_PROG ${LOCK_PROG_ARGS[*]}"
