#!/bin/bash

case "$1" in
@selection)
    input="$(wl-paste --primary)"
    ;;
@clipboard)
    input="$(wl-paste)"
    ;;
@text:*)
    input="${1:6}"
    ;;
*)
    echo 'Usage:' $0 '@selection|@clipboard|@text:<TEXT>'
    exit 1
    ;;
esac
[[ $? = 0 ]] || exit $?
input=${input%%*([[:blank:]])}
input=${input##*([[:blank:]])}

result=$(sdcv --non-interactive --non-interactive --utf8-output "$input")
[[ $? = 0 ]] || exit $?
[[ -z "$result" ]] && exit 1

exec notify-send --app-name='sdcv' 'Translate' "$result"
